import type {
  Business,
  BusinessImage,
  Category,
  City,
  District,
  Review,
} from "@/types/domain";

// -----------------------------------------------------------------------------
// Categories

export const CATEGORIES: Category[] = [
  {
    id: "cat-restaurants",
    parentId: null,
    slug: "restaurants",
    icon: "utensils",
    imageUrl: null,
    categoryType: "food",
    isActive: true,
    sortOrder: 1,
    businessCount: 1284,
    name: { tr: "Restoranlar", en: "Restaurants", ar: "المطاعم" },
  },
  {
    id: "cat-hotels",
    parentId: null,
    slug: "hotels",
    icon: "bed",
    imageUrl: null,
    categoryType: "stay",
    isActive: true,
    sortOrder: 2,
    businessCount: 642,
    name: { tr: "Oteller", en: "Hotels", ar: "الفنادق" },
  },
  {
    id: "cat-clinics",
    parentId: null,
    slug: "clinics",
    icon: "stethoscope",
    imageUrl: null,
    categoryType: "health",
    isActive: true,
    sortOrder: 3,
    businessCount: 418,
    name: { tr: "Klinikler", en: "Clinics", ar: "العيادات" },
  },
  {
    id: "cat-hospitals",
    parentId: null,
    slug: "hospitals",
    icon: "hospital",
    imageUrl: null,
    categoryType: "health",
    isActive: true,
    sortOrder: 4,
    businessCount: 96,
    name: { tr: "Hastaneler", en: "Hospitals", ar: "المستشفيات" },
  },
  {
    id: "cat-cafes",
    parentId: null,
    slug: "cafes",
    icon: "coffee",
    imageUrl: null,
    categoryType: "food",
    isActive: true,
    sortOrder: 5,
    businessCount: 812,
    name: { tr: "Kafeler", en: "Cafés", ar: "المقاهي" },
  },
  {
    id: "cat-attractions",
    parentId: null,
    slug: "attractions",
    icon: "landmark",
    imageUrl: null,
    categoryType: "tourism",
    isActive: true,
    sortOrder: 6,
    businessCount: 234,
    name: { tr: "Turistik Yerler", en: "Attractions", ar: "الأماكن السياحية" },
  },
  {
    id: "cat-beauty",
    parentId: null,
    slug: "beauty",
    icon: "sparkles",
    imageUrl: null,
    categoryType: "wellness",
    isActive: true,
    sortOrder: 7,
    businessCount: 356,
    name: { tr: "Güzellik ve Bakım", en: "Beauty & Wellness", ar: "الجمال والعناية" },
  },
  {
    id: "cat-shopping",
    parentId: null,
    slug: "shopping",
    icon: "shopping-bag",
    imageUrl: null,
    categoryType: "shopping",
    isActive: true,
    sortOrder: 8,
    businessCount: 189,
    name: { tr: "Alışveriş", en: "Shopping", ar: "التسوق" },
  },
];

const cat = (slug: string): Category => {
  const c = CATEGORIES.find((x) => x.slug === slug);
  if (!c) throw new Error(`Missing demo category: ${slug}`);
  return c;
};

// -----------------------------------------------------------------------------
// Cities & districts

export const CITIES: City[] = [
  {
    id: "city-istanbul",
    countryId: "tr",
    slug: "istanbul",
    latitude: 41.0082,
    longitude: 28.9784,
    imageUrl:
      "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    isActive: true,
    sortOrder: 1,
    businessCount: 2143,
    name: { tr: "İstanbul", en: "Istanbul", ar: "إسطنبول" },
  },
  {
    id: "city-antalya",
    countryId: "tr",
    slug: "antalya",
    latitude: 36.8969,
    longitude: 30.7133,
    imageUrl:
      "https://images.unsplash.com/photo-1589308078054-832be3c4a1e6?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    isActive: true,
    sortOrder: 2,
    businessCount: 912,
    name: { tr: "Antalya", en: "Antalya", ar: "أنطاليا" },
  },
  {
    id: "city-ankara",
    countryId: "tr",
    slug: "ankara",
    latitude: 39.9334,
    longitude: 32.8597,
    imageUrl:
      "https://images.unsplash.com/photo-1595351298020-038700609878?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    isActive: true,
    sortOrder: 3,
    businessCount: 704,
    name: { tr: "Ankara", en: "Ankara", ar: "أنقرة" },
  },
  {
    id: "city-bursa",
    countryId: "tr",
    slug: "bursa",
    latitude: 40.1826,
    longitude: 29.0665,
    imageUrl:
      "https://images.unsplash.com/photo-1600881333168-2ef49b341f30?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    isActive: true,
    sortOrder: 4,
    businessCount: 388,
    name: { tr: "Bursa", en: "Bursa", ar: "بورصة" },
  },
  {
    id: "city-izmir",
    countryId: "tr",
    slug: "izmir",
    latitude: 38.4237,
    longitude: 27.1428,
    imageUrl:
      "https://images.unsplash.com/photo-1591634616938-1dfa13ee20db?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    isActive: true,
    sortOrder: 5,
    businessCount: 620,
    name: { tr: "İzmir", en: "Izmir", ar: "إزمير" },
  },
  {
    id: "city-trabzon",
    countryId: "tr",
    slug: "trabzon",
    latitude: 41.0027,
    longitude: 39.7168,
    imageUrl:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1200&q=80",
    isFeatured: true,
    isActive: true,
    sortOrder: 6,
    businessCount: 214,
    name: { tr: "Trabzon", en: "Trabzon", ar: "طرابزون" },
  },
];

export const DISTRICTS: District[] = [
  {
    id: "dist-beyoglu",
    cityId: "city-istanbul",
    slug: "beyoglu",
    latitude: 41.0369,
    longitude: 28.9855,
    isActive: true,
    name: { tr: "Beyoğlu", en: "Beyoğlu", ar: "بيوغلو" },
  },
  {
    id: "dist-kadikoy",
    cityId: "city-istanbul",
    slug: "kadikoy",
    latitude: 40.9908,
    longitude: 29.0281,
    isActive: true,
    name: { tr: "Kadıköy", en: "Kadıköy", ar: "قاضي كوي" },
  },
  {
    id: "dist-fatih",
    cityId: "city-istanbul",
    slug: "fatih",
    latitude: 41.0186,
    longitude: 28.9394,
    isActive: true,
    name: { tr: "Fatih", en: "Fatih", ar: "الفاتح" },
  },
  {
    id: "dist-konyaalti",
    cityId: "city-antalya",
    slug: "konyaalti",
    latitude: 36.8611,
    longitude: 30.6297,
    isActive: true,
    name: { tr: "Konyaaltı", en: "Konyaaltı", ar: "كونيا التي" },
  },
  {
    id: "dist-cankaya",
    cityId: "city-ankara",
    slug: "cankaya",
    latitude: 39.9089,
    longitude: 32.8619,
    isActive: true,
    name: { tr: "Çankaya", en: "Çankaya", ar: "تشانكايا" },
  },
];

const city = (slug: string): City => {
  const c = CITIES.find((x) => x.slug === slug);
  if (!c) throw new Error(`Missing demo city: ${slug}`);
  return c;
};
const district = (slug: string): District => {
  const d = DISTRICTS.find((x) => x.slug === slug);
  if (!d) throw new Error(`Missing demo district: ${slug}`);
  return d;
};

// -----------------------------------------------------------------------------
// Image builder

let imgCounter = 0;
function galleryImages(
  businessId: string,
  placeId: string,
  urls: string[],
  storageStatus: BusinessImage["storageStatus"] = "external_only",
): BusinessImage[] {
  return urls.map((url, idx) => ({
    id: `img-${businessId}-${idx}-${++imgCounter}`,
    businessId,
    placeId,
    sourceUrl: url,
    r2Key: null,
    r2Url: null,
    storageStatus,
    imageType: idx === 0 ? "cover" : "gallery",
    isCover: idx === 0,
    sortOrder: idx,
    width: 1200,
    height: 800,
    alt: undefined,
  }));
}

// -----------------------------------------------------------------------------
// Businesses

const now = new Date().toISOString();

export const BUSINESSES: Business[] = [
  {
    id: "biz-1",
    placeId: "ChIJ_p1-DemoRest_01",
    name: "Karaköy Balıkçısı",
    slug: "karakoy-balikcisi",
    originalLanguage: "tr",
    description: {
      tr: "Karaköy'ün kalbinde, Boğaz manzaralı, geleneksel Türk deniz mahsulleri.",
      en: "In the heart of Karaköy — traditional Turkish seafood with Bosphorus views.",
      ar: "في قلب كاراكوي — أطباق بحرية تركية تقليدية مع إطلالات على البوسفور.",
    },
    primaryCategory: cat("restaurants"),
    categories: [cat("restaurants")],
    city: city("istanbul"),
    district: district("beyoglu"),
    address: "Kemankeş Mah. Kardeşim Sok. No: 45, Beyoğlu / İstanbul",
    latitude: 41.0257,
    longitude: 28.9788,
    phone: "+90 212 555 01 24",
    website: "https://example.com/karakoy-balikcisi",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.0257,28.9788",
    rating: 4.7,
    reviewCount: 1284,
    priceLevel: 3,
    status: "published",
    isFeatured: true,
    isVerified: true,
    images: galleryImages(
      "biz-1",
      "ChIJ_p1-DemoRest_01",
      [
        "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=80",
        "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1592861956120-e524fc739696?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
      ],
    ),
    openingHours: weeklyHours({ open: "12:00", close: "23:30" }),
    services: [
      { key: "reservations", value: "Yes", sortOrder: 1 },
      { key: "outdoor_seating", value: "Yes", sortOrder: 2 },
      { key: "wheelchair_accessible", value: "Yes", sortOrder: 3 },
    ],
    attributes: [
      { key: "cuisine", value: "Seafood" },
      { key: "price_range", value: "$$$" },
      { key: "dining_options", value: "Dine-in, Takeaway" },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "biz-2",
    placeId: "ChIJ_p1-DemoHotel_02",
    name: "Bosphorus Grand Palace",
    slug: "bosphorus-grand-palace",
    originalLanguage: "en",
    description: {
      en: "A refined 5-star retreat with private Bosphorus terrace, spa, and Michelin-caliber dining.",
      tr: "Özel Boğaz terası, spa ve Michelin ayarında yemek sunan zarif 5 yıldızlı bir kaçamak.",
      ar: "منتجع فاخر من فئة الخمس نجوم مع تراس خاص على البوسفور، منتجع صحي ومطعم راقٍ.",
    },
    primaryCategory: cat("hotels"),
    categories: [cat("hotels")],
    city: city("istanbul"),
    district: district("beyoglu"),
    address: "Meclis-i Mebusan Cad. No: 88, Beyoğlu / İstanbul",
    latitude: 41.0311,
    longitude: 28.9847,
    phone: "+90 212 555 07 88",
    website: "https://example.com/bosphorus-grand",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.0311,28.9847",
    rating: 4.9,
    reviewCount: 2189,
    priceLevel: 4,
    status: "published",
    isFeatured: true,
    isVerified: true,
    images: galleryImages(
      "biz-2",
      "ChIJ_p1-DemoHotel_02",
      [
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=80",
        "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80",
      ],
    ),
    openingHours: weeklyHours({ open: "00:00", close: "23:59", allDay: true }),
    services: [
      { key: "wifi", value: "Free", sortOrder: 1 },
      { key: "pool", value: "Yes", sortOrder: 2 },
      { key: "spa", value: "Yes", sortOrder: 3 },
      { key: "restaurant", value: "Yes", sortOrder: 4 },
      { key: "parking", value: "Valet", sortOrder: 5 },
    ],
    attributes: [
      { key: "stars", value: 5 },
      { key: "check_in", value: "14:00" },
      { key: "check_out", value: "12:00" },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "biz-3",
    placeId: "ChIJ_p1-DemoClinic_03",
    name: "Antalya Dental Clinic",
    slug: "antalya-dental-clinic",
    originalLanguage: "en",
    description: {
      en: "Modern dental clinic in Konyaaltı offering implants, veneers and orthodontics with multilingual staff.",
      tr: "Konyaaltı'nda implant, kaplama ve ortodonti sunan modern diş kliniği. Çok dilli personel.",
      ar: "عيادة أسنان حديثة في كونيا التي تقدم زراعة الأسنان والقشور وتقويم الأسنان مع طاقم متعدد اللغات.",
    },
    primaryCategory: cat("clinics"),
    categories: [cat("clinics")],
    city: city("antalya"),
    district: district("konyaalti"),
    address: "Uncalı Mah. 1250 Sok. No: 12, Konyaaltı / Antalya",
    latitude: 36.8637,
    longitude: 30.6485,
    phone: "+90 242 555 33 21",
    website: "https://example.com/antalya-dental",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=36.8637,30.6485",
    rating: 4.8,
    reviewCount: 512,
    priceLevel: 2,
    status: "published",
    isFeatured: true,
    isVerified: true,
    images: galleryImages(
      "biz-3",
      "ChIJ_p1-DemoClinic_03",
      [
        "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1600&q=80",
        "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1200&q=80",
      ],
    ),
    openingHours: weeklyHours({ open: "09:00", close: "19:00", closedDays: [0] }),
    services: [
      { key: "implants", value: "Yes", sortOrder: 1 },
      { key: "veneers", value: "Yes", sortOrder: 2 },
      { key: "orthodontics", value: "Yes", sortOrder: 3 },
      { key: "emergency", value: "24/7 hotline", sortOrder: 4 },
    ],
    attributes: [
      { key: "languages", value: "TR, EN, AR, RU" },
      { key: "insurance_accepted", value: true },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "biz-4",
    placeId: "ChIJ_p1-DemoCafe_04",
    name: "Kadıköy Kahve Evi",
    slug: "kadikoy-kahve-evi",
    originalLanguage: "tr",
    description: {
      tr: "Moda'da özel kavrulmuş Türk kahvesi, ev yapımı tatlılar ve sessiz bir okuma köşesi.",
      en: "House-roasted Turkish coffee, homemade desserts and a quiet reading nook in Moda.",
      ar: "قهوة تركية محمصة يومياً، حلويات منزلية وركن هادئ للقراءة في حي مودا.",
    },
    primaryCategory: cat("cafes"),
    categories: [cat("cafes")],
    city: city("istanbul"),
    district: district("kadikoy"),
    address: "Moda Cad. No: 61, Kadıköy / İstanbul",
    latitude: 40.9856,
    longitude: 29.0272,
    phone: "+90 216 555 44 12",
    website: null,
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=40.9856,29.0272",
    rating: 4.6,
    reviewCount: 987,
    priceLevel: 1,
    status: "published",
    isFeatured: true,
    isVerified: false,
    images: galleryImages(
      "biz-4",
      "ChIJ_p1-DemoCafe_04",
      [
        "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1600&q=80",
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80",
      ],
    ),
    openingHours: weeklyHours({ open: "08:00", close: "22:00" }),
    services: [
      { key: "wifi", value: "Free", sortOrder: 1 },
      { key: "outdoor_seating", value: "Yes", sortOrder: 2 },
      { key: "vegan_options", value: "Yes", sortOrder: 3 },
    ],
    attributes: [{ key: "cuisine", value: "Café" }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "biz-5",
    placeId: "ChIJ_p1-DemoAttr_05",
    name: "Kapalıçarşı Historic Bazaar",
    slug: "kapalicarsi-historic-bazaar",
    originalLanguage: "en",
    description: {
      en: "One of the world's oldest covered markets — 4,000 shops of jewelry, spices, ceramics and antiques.",
      tr: "Dünyanın en eski kapalı çarşılarından biri — 4.000 mağaza kuyum, baharat, seramik ve antika.",
      ar: "أحد أقدم الأسواق المغطاة في العالم — 4000 متجر للمجوهرات والتوابل والسيراميك والتحف.",
    },
    primaryCategory: cat("attractions"),
    categories: [cat("attractions"), cat("shopping")],
    city: city("istanbul"),
    district: district("fatih"),
    address: "Beyazıt Mah. Kalpakçılar Cad. No: 22, Fatih / İstanbul",
    latitude: 41.0106,
    longitude: 28.968,
    phone: "+90 212 555 90 12",
    website: "https://example.com/grand-bazaar",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.0106,28.968",
    rating: 4.5,
    reviewCount: 45230,
    priceLevel: null,
    status: "published",
    isFeatured: true,
    isVerified: true,
    images: galleryImages(
      "biz-5",
      "ChIJ_p1-DemoAttr_05",
      [
        "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=1600&q=80",
        "https://images.unsplash.com/photo-1520637836862-4d197d17c67a?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1518281420975-50db6e5d0a97?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1553855762-8bbecd0d5b48?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
      ],
    ),
    openingHours: weeklyHours({ open: "09:00", close: "19:00", closedDays: [0] }),
    services: [],
    attributes: [{ key: "entry_fee", value: "Free" }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "biz-6",
    placeId: "ChIJ_p1-DemoRest_06",
    name: "Çankaya Kebap Sarayı",
    slug: "cankaya-kebap-sarayi",
    originalLanguage: "tr",
    description: {
      tr: "Çankaya'nın en sevilen kebap salonu — odun ateşinde pişen adana ve urfa çeşitleri.",
      en: "Çankaya's beloved kebab house — wood-fired Adana and Urfa specialties.",
      ar: "أشهر مطعم كباب في تشانكايا — كباب أضنة وأورفة مشوي على الحطب.",
    },
    primaryCategory: cat("restaurants"),
    categories: [cat("restaurants")],
    city: city("ankara"),
    district: district("cankaya"),
    address: "Kavaklıdere Mah. Tunalı Hilmi Cad. No: 45, Çankaya / Ankara",
    latitude: 39.9061,
    longitude: 32.8623,
    phone: "+90 312 555 22 44",
    website: null,
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=39.9061,32.8623",
    rating: 4.4,
    reviewCount: 1120,
    priceLevel: 2,
    status: "published",
    isFeatured: false,
    isVerified: true,
    images: galleryImages(
      "biz-6",
      "ChIJ_p1-DemoRest_06",
      [
        "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1600&q=80",
        "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1560717845-968823efbee1?auto=format&fit=crop&w=1200&q=80",
      ],
    ),
    openingHours: weeklyHours({ open: "11:00", close: "23:00" }),
    services: [
      { key: "delivery", value: "Yes", sortOrder: 1 },
      { key: "takeaway", value: "Yes", sortOrder: 2 },
    ],
    attributes: [{ key: "cuisine", value: "Turkish, Kebab" }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "biz-7",
    placeId: "ChIJ_p1-DemoHotel_07",
    name: "Konyaaltı Beach Resort",
    slug: "konyaalti-beach-resort",
    originalLanguage: "en",
    description: {
      en: "All-inclusive beachfront resort with three pools, kids' club and direct beach access.",
      tr: "Üç havuzlu, çocuk kulüplü, denize sıfır her şey dahil sahil oteli.",
      ar: "منتجع شامل على الشاطئ مع ثلاثة مسابح ونادٍ للأطفال ومدخل مباشر إلى الشاطئ.",
    },
    primaryCategory: cat("hotels"),
    categories: [cat("hotels")],
    city: city("antalya"),
    district: district("konyaalti"),
    address: "Sarısu Mah. Sahil Yolu No: 3, Konyaaltı / Antalya",
    latitude: 36.8501,
    longitude: 30.6091,
    phone: "+90 242 555 88 90",
    website: "https://example.com/konyaalti-beach",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=36.8501,30.6091",
    rating: 4.6,
    reviewCount: 3410,
    priceLevel: 3,
    status: "published",
    isFeatured: true,
    isVerified: true,
    images: galleryImages(
      "biz-7",
      "ChIJ_p1-DemoHotel_07",
      [
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1600&q=80",
        "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
      ],
    ),
    openingHours: weeklyHours({ open: "00:00", close: "23:59", allDay: true }),
    services: [
      { key: "all_inclusive", value: "Yes", sortOrder: 1 },
      { key: "beach", value: "Private", sortOrder: 2 },
      { key: "pool", value: "3 pools", sortOrder: 3 },
    ],
    attributes: [{ key: "stars", value: 5 }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "biz-8",
    placeId: "ChIJ_p1-DemoClinic_08",
    name: "Istanbul Hair Restoration Center",
    slug: "istanbul-hair-restoration-center",
    originalLanguage: "en",
    description: {
      en: "Leading FUE and DHI hair transplant clinic with 12,000+ international patients.",
      tr: "12.000'den fazla uluslararası hastası olan öncü FUE ve DHI saç ekimi kliniği.",
      ar: "عيادة رائدة في زراعة الشعر FUE و DHI مع أكثر من 12,000 مريض دولي.",
    },
    primaryCategory: cat("clinics"),
    categories: [cat("clinics"), cat("beauty")],
    city: city("istanbul"),
    district: district("beyoglu"),
    address: "Şişli Mah. Halaskargazi Cad. No: 210, Şişli / İstanbul",
    latitude: 41.0605,
    longitude: 28.9877,
    phone: "+90 212 555 77 33",
    website: "https://example.com/istanbul-hair",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.0605,28.9877",
    rating: 4.9,
    reviewCount: 2103,
    priceLevel: 3,
    status: "published",
    isFeatured: false,
    isVerified: true,
    images: galleryImages(
      "biz-8",
      "ChIJ_p1-DemoClinic_08",
      [
        "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?auto=format&fit=crop&w=1600&q=80",
        "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1666214280557-f1b5022eb634?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=1200&q=80",
      ],
    ),
    openingHours: weeklyHours({ open: "10:00", close: "20:00", closedDays: [0] }),
    services: [
      { key: "fue", value: "Yes", sortOrder: 1 },
      { key: "dhi", value: "Yes", sortOrder: 2 },
      { key: "prp", value: "Yes", sortOrder: 3 },
      { key: "airport_pickup", value: "Included", sortOrder: 4 },
    ],
    attributes: [{ key: "languages", value: "TR, EN, AR, ES" }],
    createdAt: now,
    updatedAt: now,
  },
];

// -----------------------------------------------------------------------------
// Reviews (demo)

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    businessId: "biz-1",
    source: "google",
    externalReviewId: "g-1",
    authorName: "Mehmet Y.",
    authorAvatarUrl: null,
    rating: 5,
    reviewText:
      "Balık taze, servis çok ilgili, manzara harika. Karaköy'e her gelişimde tekrar geliyorum.",
    reviewLanguage: "tr",
    ownerReply: null,
    ownerReplyAt: null,
    reviewDate: "2025-11-02",
    createdAt: "2025-11-02T14:12:00Z",
  },
  {
    id: "rev-2",
    businessId: "biz-1",
    source: "google",
    externalReviewId: "g-2",
    authorName: "Sarah K.",
    authorAvatarUrl: null,
    rating: 5,
    reviewText:
      "Excellent seafood right at the water. The grilled sea bass and meze were exceptional.",
    reviewLanguage: "en",
    ownerReply: "Thank you Sarah — we'd love to welcome you again on your next Istanbul trip!",
    ownerReplyAt: "2025-11-10T09:00:00Z",
    reviewDate: "2025-10-28",
    createdAt: "2025-10-28T20:04:00Z",
  },
  {
    id: "rev-3",
    businessId: "biz-1",
    source: "platform",
    userId: "user-demo",
    authorName: "Ahmed R.",
    authorAvatarUrl: null,
    rating: 4,
    reviewText: "طعام ممتاز وأجواء رائعة. الأسعار مرتفعة قليلاً ولكن يستحق.",
    reviewLanguage: "ar",
    reviewDate: "2025-09-14",
    createdAt: "2025-09-14T18:22:00Z",
  },
];

// -----------------------------------------------------------------------------
// helpers

interface WeeklyOpts {
  open: string;
  close: string;
  closedDays?: number[];
  allDay?: boolean;
}
function weeklyHours(opts: WeeklyOpts) {
  const days = [0, 1, 2, 3, 4, 5, 6];
  const closed = new Set(opts.closedDays ?? []);
  return days.map((dayOfWeek, idx) => ({
    dayOfWeek,
    openTime: closed.has(dayOfWeek) ? null : opts.open,
    closeTime: closed.has(dayOfWeek) ? null : opts.close,
    isClosed: closed.has(dayOfWeek),
    rawValue: opts.allDay ? "24 hours" : undefined,
    sortOrder: idx,
  }));
}
