/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangSearchRouteImport } from './routes/$lang.search'
import { Route as LangAuthRouteImport } from './routes/$lang.auth'
import { Route as LangAuthenticatedRouteImport } from './routes/$lang._authenticated'
import { Route as LangSlugRouteImport } from './routes/$lang.$slug'
import { Route as LangPlaceSlugRouteImport } from './routes/$lang.place.$slug'
import { Route as LangAuthenticatedAdminRouteImport } from './routes/$lang._authenticated.admin'
import { Route as LangAuthenticatedAccountRouteImport } from './routes/$lang._authenticated.account'
import { Route as LangCitySlugCategorySlugRouteImport } from './routes/$lang.$citySlug.$categorySlug'
import { Route as LangAuthenticatedAdminIndexRouteImport } from './routes/$lang._authenticated.admin.index'
import { Route as LangAuthenticatedAdminUsersRouteImport } from './routes/$lang._authenticated.admin.users'
import { Route as LangAuthenticatedAdminSettingsRouteImport } from './routes/$lang._authenticated.admin.settings'
import { Route as LangAuthenticatedAdminReviewsRouteImport } from './routes/$lang._authenticated.admin.reviews'
import { Route as LangAuthenticatedAdminReportsRouteImport } from './routes/$lang._authenticated.admin.reports'
import { Route as LangAuthenticatedAdminOwnershipClaimsRouteImport } from './routes/$lang._authenticated.admin.ownership-claims'
import { Route as LangAuthenticatedAdminImportsRouteImport } from './routes/$lang._authenticated.admin.imports'
import { Route as LangAuthenticatedAdminCitiesRouteImport } from './routes/$lang._authenticated.admin.cities'
import { Route as LangAuthenticatedAdminCategoryMappingsRouteImport } from './routes/$lang._authenticated.admin.category-mappings'
import { Route as LangAuthenticatedAdminCategoriesRouteImport } from './routes/$lang._authenticated.admin.categories'
import { Route as LangAuthenticatedAdminBusinessesRouteImport } from './routes/$lang._authenticated.admin.businesses'
import { Route as LangAuthenticatedAdminAuditLogsRouteImport } from './routes/$lang._authenticated.admin.audit-logs'
import { Route as LangCitySlugDistrictSlugCategorySlugRouteImport } from './routes/$lang.$citySlug.$districtSlug.$categorySlug'
import { Route as LangAuthenticatedAdminImportsIdRouteImport } from './routes/$lang._authenticated.admin.imports.$id'
import { Route as LangAuthenticatedAdminBusinessesIdRouteImport } from './routes/$lang._authenticated.admin.businesses.$id'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangSearchRoute = LangSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthenticatedRoute = LangAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LangRoute,
} as any)
const LangSlugRoute = LangSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangPlaceSlugRoute = LangPlaceSlugRouteImport.update({
  id: '/place/$slug',
  path: '/place/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthenticatedAdminRoute = LangAuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangAuthenticatedRoute,
} as any)
const LangAuthenticatedAccountRoute =
  LangAuthenticatedAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LangAuthenticatedRoute,
  } as any)
const LangCitySlugCategorySlugRoute =
  LangCitySlugCategorySlugRouteImport.update({
    id: '/$citySlug/$categorySlug',
    path: '/$citySlug/$categorySlug',
    getParentRoute: () => LangRoute,
  } as any)
const LangAuthenticatedAdminIndexRoute =
  LangAuthenticatedAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminUsersRoute =
  LangAuthenticatedAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminSettingsRoute =
  LangAuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminReviewsRoute =
  LangAuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminReportsRoute =
  LangAuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminOwnershipClaimsRoute =
  LangAuthenticatedAdminOwnershipClaimsRouteImport.update({
    id: '/ownership-claims',
    path: '/ownership-claims',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminImportsRoute =
  LangAuthenticatedAdminImportsRouteImport.update({
    id: '/imports',
    path: '/imports',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminCitiesRoute =
  LangAuthenticatedAdminCitiesRouteImport.update({
    id: '/cities',
    path: '/cities',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminCategoryMappingsRoute =
  LangAuthenticatedAdminCategoryMappingsRouteImport.update({
    id: '/category-mappings',
    path: '/category-mappings',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminCategoriesRoute =
  LangAuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminBusinessesRoute =
  LangAuthenticatedAdminBusinessesRouteImport.update({
    id: '/businesses',
    path: '/businesses',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangAuthenticatedAdminAuditLogsRoute =
  LangAuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => LangAuthenticatedAdminRoute,
  } as any)
const LangCitySlugDistrictSlugCategorySlugRoute =
  LangCitySlugDistrictSlugCategorySlugRouteImport.update({
    id: '/$citySlug/$districtSlug/$categorySlug',
    path: '/$citySlug/$districtSlug/$categorySlug',
    getParentRoute: () => LangRoute,
  } as any)
const LangAuthenticatedAdminImportsIdRoute =
  LangAuthenticatedAdminImportsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => LangAuthenticatedAdminImportsRoute,
  } as any)
const LangAuthenticatedAdminBusinessesIdRoute =
  LangAuthenticatedAdminBusinessesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => LangAuthenticatedAdminBusinessesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/$slug': typeof LangSlugRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/$citySlug/$categorySlug': typeof LangCitySlugCategorySlugRoute
  '/$lang/account': typeof LangAuthenticatedAccountRoute
  '/$lang/admin': typeof LangAuthenticatedAdminRouteWithChildren
  '/$lang/place/$slug': typeof LangPlaceSlugRoute
  '/$lang/$citySlug/$districtSlug/$categorySlug': typeof LangCitySlugDistrictSlugCategorySlugRoute
  '/$lang/admin/audit-logs': typeof LangAuthenticatedAdminAuditLogsRoute
  '/$lang/admin/businesses': typeof LangAuthenticatedAdminBusinessesRouteWithChildren
  '/$lang/admin/categories': typeof LangAuthenticatedAdminCategoriesRoute
  '/$lang/admin/category-mappings': typeof LangAuthenticatedAdminCategoryMappingsRoute
  '/$lang/admin/cities': typeof LangAuthenticatedAdminCitiesRoute
  '/$lang/admin/imports': typeof LangAuthenticatedAdminImportsRouteWithChildren
  '/$lang/admin/ownership-claims': typeof LangAuthenticatedAdminOwnershipClaimsRoute
  '/$lang/admin/reports': typeof LangAuthenticatedAdminReportsRoute
  '/$lang/admin/reviews': typeof LangAuthenticatedAdminReviewsRoute
  '/$lang/admin/settings': typeof LangAuthenticatedAdminSettingsRoute
  '/$lang/admin/users': typeof LangAuthenticatedAdminUsersRoute
  '/$lang/admin/': typeof LangAuthenticatedAdminIndexRoute
  '/$lang/admin/businesses/$id': typeof LangAuthenticatedAdminBusinessesIdRoute
  '/$lang/admin/imports/$id': typeof LangAuthenticatedAdminImportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/$slug': typeof LangSlugRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/$citySlug/$categorySlug': typeof LangCitySlugCategorySlugRoute
  '/$lang/account': typeof LangAuthenticatedAccountRoute
  '/$lang/place/$slug': typeof LangPlaceSlugRoute
  '/$lang/$citySlug/$districtSlug/$categorySlug': typeof LangCitySlugDistrictSlugCategorySlugRoute
  '/$lang/admin/audit-logs': typeof LangAuthenticatedAdminAuditLogsRoute
  '/$lang/admin/businesses': typeof LangAuthenticatedAdminBusinessesRouteWithChildren
  '/$lang/admin/categories': typeof LangAuthenticatedAdminCategoriesRoute
  '/$lang/admin/category-mappings': typeof LangAuthenticatedAdminCategoryMappingsRoute
  '/$lang/admin/cities': typeof LangAuthenticatedAdminCitiesRoute
  '/$lang/admin/imports': typeof LangAuthenticatedAdminImportsRouteWithChildren
  '/$lang/admin/ownership-claims': typeof LangAuthenticatedAdminOwnershipClaimsRoute
  '/$lang/admin/reports': typeof LangAuthenticatedAdminReportsRoute
  '/$lang/admin/reviews': typeof LangAuthenticatedAdminReviewsRoute
  '/$lang/admin/settings': typeof LangAuthenticatedAdminSettingsRoute
  '/$lang/admin/users': typeof LangAuthenticatedAdminUsersRoute
  '/$lang/admin': typeof LangAuthenticatedAdminIndexRoute
  '/$lang/admin/businesses/$id': typeof LangAuthenticatedAdminBusinessesIdRoute
  '/$lang/admin/imports/$id': typeof LangAuthenticatedAdminImportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/$slug': typeof LangSlugRoute
  '/$lang/_authenticated': typeof LangAuthenticatedRouteWithChildren
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/$citySlug/$categorySlug': typeof LangCitySlugCategorySlugRoute
  '/$lang/_authenticated/account': typeof LangAuthenticatedAccountRoute
  '/$lang/_authenticated/admin': typeof LangAuthenticatedAdminRouteWithChildren
  '/$lang/place/$slug': typeof LangPlaceSlugRoute
  '/$lang/$citySlug/$districtSlug/$categorySlug': typeof LangCitySlugDistrictSlugCategorySlugRoute
  '/$lang/_authenticated/admin/audit-logs': typeof LangAuthenticatedAdminAuditLogsRoute
  '/$lang/_authenticated/admin/businesses': typeof LangAuthenticatedAdminBusinessesRouteWithChildren
  '/$lang/_authenticated/admin/categories': typeof LangAuthenticatedAdminCategoriesRoute
  '/$lang/_authenticated/admin/category-mappings': typeof LangAuthenticatedAdminCategoryMappingsRoute
  '/$lang/_authenticated/admin/cities': typeof LangAuthenticatedAdminCitiesRoute
  '/$lang/_authenticated/admin/imports': typeof LangAuthenticatedAdminImportsRouteWithChildren
  '/$lang/_authenticated/admin/ownership-claims': typeof LangAuthenticatedAdminOwnershipClaimsRoute
  '/$lang/_authenticated/admin/reports': typeof LangAuthenticatedAdminReportsRoute
  '/$lang/_authenticated/admin/reviews': typeof LangAuthenticatedAdminReviewsRoute
  '/$lang/_authenticated/admin/settings': typeof LangAuthenticatedAdminSettingsRoute
  '/$lang/_authenticated/admin/users': typeof LangAuthenticatedAdminUsersRoute
  '/$lang/_authenticated/admin/': typeof LangAuthenticatedAdminIndexRoute
  '/$lang/_authenticated/admin/businesses/$id': typeof LangAuthenticatedAdminBusinessesIdRoute
  '/$lang/_authenticated/admin/imports/$id': typeof LangAuthenticatedAdminImportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/$slug'
    | '/$lang/auth'
    | '/$lang/search'
    | '/$lang/'
    | '/$lang/$citySlug/$categorySlug'
    | '/$lang/account'
    | '/$lang/admin'
    | '/$lang/place/$slug'
    | '/$lang/$citySlug/$districtSlug/$categorySlug'
    | '/$lang/admin/audit-logs'
    | '/$lang/admin/businesses'
    | '/$lang/admin/categories'
    | '/$lang/admin/category-mappings'
    | '/$lang/admin/cities'
    | '/$lang/admin/imports'
    | '/$lang/admin/ownership-claims'
    | '/$lang/admin/reports'
    | '/$lang/admin/reviews'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin/'
    | '/$lang/admin/businesses/$id'
    | '/$lang/admin/imports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/$slug'
    | '/$lang'
    | '/$lang/auth'
    | '/$lang/search'
    | '/$lang/$citySlug/$categorySlug'
    | '/$lang/account'
    | '/$lang/place/$slug'
    | '/$lang/$citySlug/$districtSlug/$categorySlug'
    | '/$lang/admin/audit-logs'
    | '/$lang/admin/businesses'
    | '/$lang/admin/categories'
    | '/$lang/admin/category-mappings'
    | '/$lang/admin/cities'
    | '/$lang/admin/imports'
    | '/$lang/admin/ownership-claims'
    | '/$lang/admin/reports'
    | '/$lang/admin/reviews'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin'
    | '/$lang/admin/businesses/$id'
    | '/$lang/admin/imports/$id'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/$slug'
    | '/$lang/_authenticated'
    | '/$lang/auth'
    | '/$lang/search'
    | '/$lang/'
    | '/$lang/$citySlug/$categorySlug'
    | '/$lang/_authenticated/account'
    | '/$lang/_authenticated/admin'
    | '/$lang/place/$slug'
    | '/$lang/$citySlug/$districtSlug/$categorySlug'
    | '/$lang/_authenticated/admin/audit-logs'
    | '/$lang/_authenticated/admin/businesses'
    | '/$lang/_authenticated/admin/categories'
    | '/$lang/_authenticated/admin/category-mappings'
    | '/$lang/_authenticated/admin/cities'
    | '/$lang/_authenticated/admin/imports'
    | '/$lang/_authenticated/admin/ownership-claims'
    | '/$lang/_authenticated/admin/reports'
    | '/$lang/_authenticated/admin/reviews'
    | '/$lang/_authenticated/admin/settings'
    | '/$lang/_authenticated/admin/users'
    | '/$lang/_authenticated/admin/'
    | '/$lang/_authenticated/admin/businesses/$id'
    | '/$lang/_authenticated/admin/imports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/search': {
      id: '/$lang/search'
      path: '/search'
      fullPath: '/$lang/search'
      preLoaderRoute: typeof LangSearchRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_authenticated': {
      id: '/$lang/_authenticated'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthenticatedRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/$slug': {
      id: '/$lang/$slug'
      path: '/$slug'
      fullPath: '/$lang/$slug'
      preLoaderRoute: typeof LangSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/place/$slug': {
      id: '/$lang/place/$slug'
      path: '/place/$slug'
      fullPath: '/$lang/place/$slug'
      preLoaderRoute: typeof LangPlaceSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_authenticated/admin': {
      id: '/$lang/_authenticated/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAuthenticatedAdminRouteImport
      parentRoute: typeof LangAuthenticatedRoute
    }
    '/$lang/_authenticated/account': {
      id: '/$lang/_authenticated/account'
      path: '/account'
      fullPath: '/$lang/account'
      preLoaderRoute: typeof LangAuthenticatedAccountRouteImport
      parentRoute: typeof LangAuthenticatedRoute
    }
    '/$lang/$citySlug/$categorySlug': {
      id: '/$lang/$citySlug/$categorySlug'
      path: '/$citySlug/$categorySlug'
      fullPath: '/$lang/$citySlug/$categorySlug'
      preLoaderRoute: typeof LangCitySlugCategorySlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_authenticated/admin/': {
      id: '/$lang/_authenticated/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAuthenticatedAdminIndexRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/users': {
      id: '/$lang/_authenticated/admin/users'
      path: '/users'
      fullPath: '/$lang/admin/users'
      preLoaderRoute: typeof LangAuthenticatedAdminUsersRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/settings': {
      id: '/$lang/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/$lang/admin/settings'
      preLoaderRoute: typeof LangAuthenticatedAdminSettingsRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/reviews': {
      id: '/$lang/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/$lang/admin/reviews'
      preLoaderRoute: typeof LangAuthenticatedAdminReviewsRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/reports': {
      id: '/$lang/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/$lang/admin/reports'
      preLoaderRoute: typeof LangAuthenticatedAdminReportsRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/ownership-claims': {
      id: '/$lang/_authenticated/admin/ownership-claims'
      path: '/ownership-claims'
      fullPath: '/$lang/admin/ownership-claims'
      preLoaderRoute: typeof LangAuthenticatedAdminOwnershipClaimsRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/imports': {
      id: '/$lang/_authenticated/admin/imports'
      path: '/imports'
      fullPath: '/$lang/admin/imports'
      preLoaderRoute: typeof LangAuthenticatedAdminImportsRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/cities': {
      id: '/$lang/_authenticated/admin/cities'
      path: '/cities'
      fullPath: '/$lang/admin/cities'
      preLoaderRoute: typeof LangAuthenticatedAdminCitiesRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/category-mappings': {
      id: '/$lang/_authenticated/admin/category-mappings'
      path: '/category-mappings'
      fullPath: '/$lang/admin/category-mappings'
      preLoaderRoute: typeof LangAuthenticatedAdminCategoryMappingsRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/categories': {
      id: '/$lang/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/$lang/admin/categories'
      preLoaderRoute: typeof LangAuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/businesses': {
      id: '/$lang/_authenticated/admin/businesses'
      path: '/businesses'
      fullPath: '/$lang/admin/businesses'
      preLoaderRoute: typeof LangAuthenticatedAdminBusinessesRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/_authenticated/admin/audit-logs': {
      id: '/$lang/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/$lang/admin/audit-logs'
      preLoaderRoute: typeof LangAuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof LangAuthenticatedAdminRoute
    }
    '/$lang/$citySlug/$districtSlug/$categorySlug': {
      id: '/$lang/$citySlug/$districtSlug/$categorySlug'
      path: '/$citySlug/$districtSlug/$categorySlug'
      fullPath: '/$lang/$citySlug/$districtSlug/$categorySlug'
      preLoaderRoute: typeof LangCitySlugDistrictSlugCategorySlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_authenticated/admin/imports/$id': {
      id: '/$lang/_authenticated/admin/imports/$id'
      path: '/$id'
      fullPath: '/$lang/admin/imports/$id'
      preLoaderRoute: typeof LangAuthenticatedAdminImportsIdRouteImport
      parentRoute: typeof LangAuthenticatedAdminImportsRoute
    }
    '/$lang/_authenticated/admin/businesses/$id': {
      id: '/$lang/_authenticated/admin/businesses/$id'
      path: '/$id'
      fullPath: '/$lang/admin/businesses/$id'
      preLoaderRoute: typeof LangAuthenticatedAdminBusinessesIdRouteImport
      parentRoute: typeof LangAuthenticatedAdminBusinessesRoute
    }
  }
}

interface LangAuthenticatedAdminBusinessesRouteChildren {
  LangAuthenticatedAdminBusinessesIdRoute: typeof LangAuthenticatedAdminBusinessesIdRoute
}

const LangAuthenticatedAdminBusinessesRouteChildren: LangAuthenticatedAdminBusinessesRouteChildren =
  {
    LangAuthenticatedAdminBusinessesIdRoute:
      LangAuthenticatedAdminBusinessesIdRoute,
  }

const LangAuthenticatedAdminBusinessesRouteWithChildren =
  LangAuthenticatedAdminBusinessesRoute._addFileChildren(
    LangAuthenticatedAdminBusinessesRouteChildren,
  )

interface LangAuthenticatedAdminImportsRouteChildren {
  LangAuthenticatedAdminImportsIdRoute: typeof LangAuthenticatedAdminImportsIdRoute
}

const LangAuthenticatedAdminImportsRouteChildren: LangAuthenticatedAdminImportsRouteChildren =
  {
    LangAuthenticatedAdminImportsIdRoute: LangAuthenticatedAdminImportsIdRoute,
  }

const LangAuthenticatedAdminImportsRouteWithChildren =
  LangAuthenticatedAdminImportsRoute._addFileChildren(
    LangAuthenticatedAdminImportsRouteChildren,
  )

interface LangAuthenticatedAdminRouteChildren {
  LangAuthenticatedAdminAuditLogsRoute: typeof LangAuthenticatedAdminAuditLogsRoute
  LangAuthenticatedAdminBusinessesRoute: typeof LangAuthenticatedAdminBusinessesRouteWithChildren
  LangAuthenticatedAdminCategoriesRoute: typeof LangAuthenticatedAdminCategoriesRoute
  LangAuthenticatedAdminCategoryMappingsRoute: typeof LangAuthenticatedAdminCategoryMappingsRoute
  LangAuthenticatedAdminCitiesRoute: typeof LangAuthenticatedAdminCitiesRoute
  LangAuthenticatedAdminImportsRoute: typeof LangAuthenticatedAdminImportsRouteWithChildren
  LangAuthenticatedAdminOwnershipClaimsRoute: typeof LangAuthenticatedAdminOwnershipClaimsRoute
  LangAuthenticatedAdminReportsRoute: typeof LangAuthenticatedAdminReportsRoute
  LangAuthenticatedAdminReviewsRoute: typeof LangAuthenticatedAdminReviewsRoute
  LangAuthenticatedAdminSettingsRoute: typeof LangAuthenticatedAdminSettingsRoute
  LangAuthenticatedAdminUsersRoute: typeof LangAuthenticatedAdminUsersRoute
  LangAuthenticatedAdminIndexRoute: typeof LangAuthenticatedAdminIndexRoute
}

const LangAuthenticatedAdminRouteChildren: LangAuthenticatedAdminRouteChildren =
  {
    LangAuthenticatedAdminAuditLogsRoute: LangAuthenticatedAdminAuditLogsRoute,
    LangAuthenticatedAdminBusinessesRoute:
      LangAuthenticatedAdminBusinessesRouteWithChildren,
    LangAuthenticatedAdminCategoriesRoute:
      LangAuthenticatedAdminCategoriesRoute,
    LangAuthenticatedAdminCategoryMappingsRoute:
      LangAuthenticatedAdminCategoryMappingsRoute,
    LangAuthenticatedAdminCitiesRoute: LangAuthenticatedAdminCitiesRoute,
    LangAuthenticatedAdminImportsRoute:
      LangAuthenticatedAdminImportsRouteWithChildren,
    LangAuthenticatedAdminOwnershipClaimsRoute:
      LangAuthenticatedAdminOwnershipClaimsRoute,
    LangAuthenticatedAdminReportsRoute: LangAuthenticatedAdminReportsRoute,
    LangAuthenticatedAdminReviewsRoute: LangAuthenticatedAdminReviewsRoute,
    LangAuthenticatedAdminSettingsRoute: LangAuthenticatedAdminSettingsRoute,
    LangAuthenticatedAdminUsersRoute: LangAuthenticatedAdminUsersRoute,
    LangAuthenticatedAdminIndexRoute: LangAuthenticatedAdminIndexRoute,
  }

const LangAuthenticatedAdminRouteWithChildren =
  LangAuthenticatedAdminRoute._addFileChildren(
    LangAuthenticatedAdminRouteChildren,
  )

interface LangAuthenticatedRouteChildren {
  LangAuthenticatedAccountRoute: typeof LangAuthenticatedAccountRoute
  LangAuthenticatedAdminRoute: typeof LangAuthenticatedAdminRouteWithChildren
}

const LangAuthenticatedRouteChildren: LangAuthenticatedRouteChildren = {
  LangAuthenticatedAccountRoute: LangAuthenticatedAccountRoute,
  LangAuthenticatedAdminRoute: LangAuthenticatedAdminRouteWithChildren,
}

const LangAuthenticatedRouteWithChildren =
  LangAuthenticatedRoute._addFileChildren(LangAuthenticatedRouteChildren)

interface LangRouteChildren {
  LangSlugRoute: typeof LangSlugRoute
  LangAuthenticatedRoute: typeof LangAuthenticatedRouteWithChildren
  LangAuthRoute: typeof LangAuthRoute
  LangSearchRoute: typeof LangSearchRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCitySlugCategorySlugRoute: typeof LangCitySlugCategorySlugRoute
  LangPlaceSlugRoute: typeof LangPlaceSlugRoute
  LangCitySlugDistrictSlugCategorySlugRoute: typeof LangCitySlugDistrictSlugCategorySlugRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangSlugRoute: LangSlugRoute,
  LangAuthenticatedRoute: LangAuthenticatedRouteWithChildren,
  LangAuthRoute: LangAuthRoute,
  LangSearchRoute: LangSearchRoute,
  LangIndexRoute: LangIndexRoute,
  LangCitySlugCategorySlugRoute: LangCitySlugCategorySlugRoute,
  LangPlaceSlugRoute: LangPlaceSlugRoute,
  LangCitySlugDistrictSlugCategorySlugRoute:
    LangCitySlugDistrictSlugCategorySlugRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
